using AutoMapper;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyDishesAPI.DbContexts;
using MyDishesAPI.Entities;
using MyDishesAPI.Extensions;
using MyDishesAPI.Models;
using System.Security.Claims;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container

// register the DbContext on the container, getting the connection string from appsettings.json
builder.Services.AddDbContext<MyDishesDbContext>(options =>
    options.UseSqlite(builder.Configuration.GetConnectionString("MyDishesDbContext"))); // Kevin had "ConnectionStrings:DishesDBConnectionString"

builder.Services.AddAutoMapper(AppDomain.CurrentDomain.GetAssemblies());

builder.Services.AddProblemDetails(); // This is for the exception handler

builder.Services.AddAuthentication().AddJwtBearer();
builder.Services.AddAuthorization();

builder.Services.AddAuthorizationBuilder()  // Kevin entered this code to add policies
    .AddPolicy("RequireAdminFromBelgium",
        policy => policy
        .RequireRole("Admin")
        .RequireClaim(ClaimTypes.Country, "Belgium"));  // Note: Kevin had this for this line: .RequireClaim("country", "Belgium");

builder.Services.AddEndpointsApiExplorer(); // This is for the OpenAPI/Swagger documentation
builder.Services.AddSwaggerGen(); // This is for Swagger UI

var app = builder.Build();

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler();
    //app.UseExceptionHandler(configureApplicationBuilder =>
    //{
    //    configureApplicationBuilder.Run(async context =>
    //    {
    //        context.Response.StatusCode = StatusCodes.Status500InternalServerError; // Kevin had context.Response.StatusCode = (int)HttpStatusCode.InternalServerError;
    //        context.Response.ContentType = "text/html";  // GH Copilot had "application/json"
    //        await context.Response.WriteAsync("An unexpected error occurred. Please try again later.");
    //    });
    //});
}


app.UseHttpsRedirection();

// The next two lines are for the OpenAPI/Swagger documentation. Kevin only had app.UseSwaggerUI(); GH Copilot added the rest. If I have any problems with Swagger, I will comment out those additional lines..
app.UseSwagger(); // This is for the OpenAPI/Swagger documentation
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My Dishes API V1");
    c.RoutePrefix = string.Empty; // This makes Swagger UI available at the app's root
});
//app.UseSwaggerUI(); // This is what Kevin had, but it didn't work for me. All I got was the JSON output, which is what the above app.UseSwaggerUI() code generated by GH Copilot gave me. So, I'll switch back to that.

app.UseAuthentication();
app.UseAuthorization();

app.RegisterDishesEndpoints(); 
app.RegisterIngredientsEndpoints(); 

// recreate & migrate the database on each run, for demo purposes
using (var serviceScope = app.Services.GetService<IServiceScopeFactory>()?.CreateScope())
{
    var context = serviceScope?.ServiceProvider.GetRequiredService<MyDishesDbContext>();
    context?.Database.EnsureDeleted();
    context?.Database.Migrate();
}

app.Run();
