# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build MyDishesAPI on Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
        SOLUTION_LOCATION: MyDishesAPI.sln

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies ${{ env.SOLUTION_LOCATION }}
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ${{ env.SOLUTION_LOCATION }}
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
